const AUDIT_ACTIONS = {
  // Auth
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',

  // Students
  CREATE_STUDENT: 'CREATE_STUDENT',
  UPDATE_STUDENT: 'UPDATE_STUDENT',
  DELETE_STUDENT: 'DELETE_STUDENT',
  BULK_IMPORT_STUDENTS: 'BULK_IMPORT_STUDENTS',
  PROMOTE_STUDENT: 'PROMOTE_STUDENT',

  // Examination Scheme & Config
  CREATE_SCHEME: 'CREATE_SCHEME',
  UPDATE_SCHEME: 'UPDATE_SCHEME',
  CREATE_GRADE_RULE: 'CREATE_GRADE_RULE',
  UPDATE_GRADE_RULE: 'UPDATE_GRADE_RULE',

  // Marks
  ENTER_MARKS: 'ENTER_MARKS',
  UPDATE_MARKS: 'UPDATE_MARKS',
  BULK_IMPORT_MARKS: 'BULK_IMPORT_MARKS',
  LOCK_MARKS: 'LOCK_MARKS',
  UNLOCK_MARKS: 'UNLOCK_MARKS',

  // Results
  CALCULATE_RESULT: 'CALCULATE_RESULT',
  SUBMIT_RESULT: 'SUBMIT_RESULT',
  VERIFY_RESULT: 'VERIFY_RESULT',
  APPROVE_RESULT: 'APPROVE_RESULT',
  PUBLISH_RESULT: 'PUBLISH_RESULT',
  REOPEN_RESULT: 'REOPEN_RESULT',

  // External / Board
  IMPORT_EXTERNAL_RESULT: 'IMPORT_EXTERNAL_RESULT',
  UPDATE_EXTERNAL_RESULT: 'UPDATE_EXTERNAL_RESULT',

  // Settings
  UPDATE_SETTINGS: 'UPDATE_SETTINGS',
  BACKUP_CREATED: 'BACKUP_CREATED',
  RESTORE_EXECUTED: 'RESTORE_EXECUTED'
};

module.exports = {
  AUDIT_ACTIONS
};
