const EXAMINATION_TYPES = {
  FORMATIVE: 'FORMATIVE',             // Periodic Test, Unit Test, Monthly Evaluation
  SUMMATIVE: 'SUMMATIVE',             // Half-Yearly, Annual
  PRACTICAL_PROJECT: 'PRACTICAL_PROJECT',
  CO_SCHOLASTIC: 'CO_SCHOLASTIC',
  EXTERNAL_BOARD: 'EXTERNAL_BOARD'    // Class 5/8 External Authority, Class 10/12 Board
};

const COMPONENT_TYPES = {
  THEORY: 'THEORY',
  PRACTICAL: 'PRACTICAL',
  PROJECT: 'PROJECT',
  INTERNAL_ASSESSMENT: 'INTERNAL_ASSESSMENT',
  ORAL: 'ORAL',
  NOTEBOOK: 'NOTEBOOK',
  PERIODIC_TEST: 'PERIODIC_TEST',
  ACTIVITY: 'ACTIVITY',
  CO_CURRICULAR: 'CO_CURRICULAR'
};

const ATTENDANCE_STATUSES = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  EXEMPTED: 'EXEMPTED',
  NOT_APPEARED: 'NOT_APPEARED',
  WITHHELD: 'WITHHELD',
  MEDICAL_LEAVE: 'MEDICAL_LEAVE'
};

const CLASS_MODES = {
  PRIMARY_SCHOOL: 'PRIMARY_SCHOOL',       // Classes 1-4
  EXTERNAL_AUTHORITY: 'EXTERNAL_AUTHORITY', // Class 5 & 8
  MIDDLE_SCHOOL: 'MIDDLE_SCHOOL',         // Classes 6-7
  MP_ACADEMIC: 'MP_ACADEMIC',             // Class 9 (flexible theory/practical max marks)
  MP_BOARD_EXTERNAL: 'MP_BOARD_EXTERNAL', // Class 10 (external/board record reference)
  MP_STREAM_ACADEMIC: 'MP_STREAM_ACADEMIC' // Class 11 & 12 (Science, Commerce, Arts)
};

module.exports = {
  EXAMINATION_TYPES,
  COMPONENT_TYPES,
  ATTENDANCE_STATUSES,
  CLASS_MODES
};
