const RESULT_STATUSES = {
  PASS: 'PASS',
  FAIL: 'FAIL',
  PROMOTED: 'PROMOTED',
  NOT_PROMOTED: 'NOT_PROMOTED',
  SUPPLEMENTARY: 'SUPPLEMENTARY',
  COMPARTMENT: 'COMPARTMENT',
  WITHHELD: 'WITHHELD',
  ABSENT: 'ABSENT',
  CANCELLED: 'CANCELLED',
  PENDING: 'PENDING'
};

const APPROVAL_STAGES = {
  DRAFT: 'DRAFT',
  TEACHER_SUBMITTED: 'TEACHER_SUBMITTED',
  EXAMINATION_VERIFIED: 'EXAMINATION_VERIFIED',
  PRINCIPAL_APPROVED: 'PRINCIPAL_APPROVED',
  PUBLISHED: 'PUBLISHED'
};

module.exports = {
  RESULT_STATUSES,
  APPROVAL_STAGES
};
