const ROLES = {
  ADMIN: 'ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  EXAM_INCHARGE: 'EXAM_INCHARGE',
  TEACHER: 'TEACHER',
  STAFF: 'STAFF',
  STUDENT: 'STUDENT'
};

const PERMISSIONS = {
  // Academic Setup
  MANAGE_SESSIONS: 'MANAGE_SESSIONS',
  MANAGE_CLASSES: 'MANAGE_CLASSES',
  MANAGE_SUBJECTS: 'MANAGE_SUBJECTS',
  MANAGE_SCHEMES: 'MANAGE_SCHEMES',
  MANAGE_GRADE_RULES: 'MANAGE_GRADE_RULES',

  // Student Management
  MANAGE_STUDENTS: 'MANAGE_STUDENTS',
  VIEW_STUDENTS: 'VIEW_STUDENTS',
  PROMOTE_STUDENTS: 'PROMOTE_STUDENTS',

  // Examination & Marks
  MANAGE_EXAMS: 'MANAGE_EXAMS',
  ENTER_MARKS: 'ENTER_MARKS',
  LOCK_EXAMS: 'LOCK_EXAMS',

  // Results & Approvals
  CALCULATE_RESULTS: 'CALCULATE_RESULTS',
  SUBMIT_RESULTS: 'SUBMIT_RESULTS',
  VERIFY_RESULTS: 'VERIFY_RESULTS',
  APPROVE_RESULTS: 'APPROVE_RESULTS',
  PUBLISH_RESULTS: 'PUBLISH_RESULTS',
  REOPEN_RESULTS: 'REOPEN_RESULTS',

  // External / Board Results
  MANAGE_EXTERNAL_RESULTS: 'MANAGE_EXTERNAL_RESULTS',

  // Reports & Analytics
  VIEW_REPORTS: 'VIEW_REPORTS',
  GENERATE_MARKSHEETS: 'GENERATE_MARKSHEETS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',

  // Administration
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PRINCIPAL]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.PROMOTE_STUDENTS,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.LOCK_EXAMS,
    PERMISSIONS.CALCULATE_RESULTS,
    PERMISSIONS.VERIFY_RESULTS,
    PERMISSIONS.APPROVE_RESULTS,
    PERMISSIONS.PUBLISH_RESULTS,
    PERMISSIONS.REOPEN_RESULTS,
    PERMISSIONS.MANAGE_EXTERNAL_RESULTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_SETTINGS
  ],
  [ROLES.EXAM_INCHARGE]: [
    PERMISSIONS.MANAGE_SESSIONS,
    PERMISSIONS.MANAGE_CLASSES,
    PERMISSIONS.MANAGE_SUBJECTS,
    PERMISSIONS.MANAGE_SCHEMES,
    PERMISSIONS.MANAGE_GRADE_RULES,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.PROMOTE_STUDENTS,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.ENTER_MARKS,
    PERMISSIONS.LOCK_EXAMS,
    PERMISSIONS.CALCULATE_RESULTS,
    PERMISSIONS.SUBMIT_RESULTS,
    PERMISSIONS.VERIFY_RESULTS,
    PERMISSIONS.MANAGE_EXTERNAL_RESULTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS,
    PERMISSIONS.VIEW_ANALYTICS
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.ENTER_MARKS,
    PERMISSIONS.CALCULATE_RESULTS,
    PERMISSIONS.SUBMIT_RESULTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_REPORTS
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};
