const ROLES = {
  ADMIN: 'ADMIN',
  PRINCIPAL: 'PRINCIPAL',
  ACCOUNTANT: 'ACCOUNTANT',
  TEACHER: 'TEACHER',
  STAFF: 'STAFF',
  PARENT: 'PARENT',
  STUDENT: 'STUDENT'
};

const PERMISSIONS = {
  // Academic Setup
  MANAGE_SESSIONS: 'MANAGE_SESSIONS',
  MANAGE_CLASSES: 'MANAGE_CLASSES',
  MANAGE_SUBJECTS: 'MANAGE_SUBJECTS',
  MANAGE_SCHEMES: 'MANAGE_SCHEMES',
  MANAGE_GRADE_RULES: 'MANAGE_GRADE_RULES',

  // Admissions & Students
  MANAGE_ADMISSIONS: 'MANAGE_ADMISSIONS',
  VIEW_ADMISSIONS: 'VIEW_ADMISSIONS',
  MANAGE_STUDENTS: 'MANAGE_STUDENTS',
  VIEW_STUDENTS: 'VIEW_STUDENTS',
  PROMOTE_STUDENTS: 'PROMOTE_STUDENTS',

  // Staff & HR
  MANAGE_STAFF: 'MANAGE_STAFF',
  VIEW_STAFF: 'VIEW_STAFF',
  MANAGE_ALLOCATIONS: 'MANAGE_ALLOCATIONS',

  // Daily Operations
  MARK_ATTENDANCE: 'MARK_ATTENDANCE',
  VIEW_ATTENDANCE: 'VIEW_ATTENDANCE',
  MANAGE_TIMETABLE: 'MANAGE_TIMETABLE',
  VIEW_TIMETABLE: 'VIEW_TIMETABLE',
  MANAGE_HOMEWORK: 'MANAGE_HOMEWORK',
  VIEW_HOMEWORK: 'VIEW_HOMEWORK',

  // Fees & Finance
  MANAGE_FEE_STRUCTURES: 'MANAGE_FEE_STRUCTURES',
  COLLECT_FEES: 'COLLECT_FEES',
  VIEW_FEES: 'VIEW_FEES',
  DISCOUNT_FEES: 'DISCOUNT_FEES',
  VIEW_FINANCIAL_REPORTS: 'VIEW_FINANCIAL_REPORTS',

  // Examination & Marks
  MANAGE_EXAMS: 'MANAGE_EXAMS',
  ENTER_MARKS: 'ENTER_MARKS',
  LOCK_EXAMS: 'LOCK_EXAMS',

  // Results & Approvals
  CALCULATE_RESULTS: 'CALCULATE_RESULTS',
  SUBMIT_RESULTS: 'SUBMIT_RESULTS',
  VERIFY_RESULTS: 'VERIFY_RESULTS',
  APPROVE_RESULTS: 'APPROVE_RESULTS',
  PUBLISH_RESULTS: 'PUBLISH_RESULTS',
  REOPEN_RESULTS: 'REOPEN_RESULTS',

  // External / Board Results
  MANAGE_EXTERNAL_RESULTS: 'MANAGE_EXTERNAL_RESULTS',

  // Communication & Certificates
  MANAGE_COMMUNICATION: 'MANAGE_COMMUNICATION',
  VIEW_COMMUNICATION: 'VIEW_COMMUNICATION',
  MANAGE_CERTIFICATES: 'MANAGE_CERTIFICATES',
  VIEW_CERTIFICATES: 'VIEW_CERTIFICATES',

  // Reports & Analytics
  VIEW_REPORTS: 'VIEW_REPORTS',
  GENERATE_MARKSHEETS: 'GENERATE_MARKSHEETS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',

  // Administration
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_SETTINGS: 'MANAGE_SETTINGS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS'
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.PRINCIPAL]: [
    PERMISSIONS.VIEW_ADMISSIONS,
    PERMISSIONS.MANAGE_ADMISSIONS,
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.PROMOTE_STUDENTS,
    PERMISSIONS.VIEW_STAFF,
    PERMISSIONS.MANAGE_STAFF,
    PERMISSIONS.MANAGE_ALLOCATIONS,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.MANAGE_TIMETABLE,
    PERMISSIONS.VIEW_TIMETABLE,
    PERMISSIONS.VIEW_HOMEWORK,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.COLLECT_FEES,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.MANAGE_EXAMS,
    PERMISSIONS.LOCK_EXAMS,
    PERMISSIONS.CALCULATE_RESULTS,
    PERMISSIONS.VERIFY_RESULTS,
    PERMISSIONS.APPROVE_RESULTS,
    PERMISSIONS.PUBLISH_RESULTS,
    PERMISSIONS.REOPEN_RESULTS,
    PERMISSIONS.MANAGE_EXTERNAL_RESULTS,
    PERMISSIONS.MANAGE_COMMUNICATION,
    PERMISSIONS.VIEW_COMMUNICATION,
    PERMISSIONS.MANAGE_CERTIFICATES,
    PERMISSIONS.VIEW_CERTIFICATES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.MANAGE_SETTINGS
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.MANAGE_FEE_STRUCTURES,
    PERMISSIONS.COLLECT_FEES,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.DISCOUNT_FEES,
    PERMISSIONS.VIEW_FINANCIAL_REPORTS,
    PERMISSIONS.VIEW_CERTIFICATES,
    PERMISSIONS.MANAGE_CERTIFICATES,
    PERMISSIONS.VIEW_REPORTS
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_TIMETABLE,
    PERMISSIONS.MANAGE_HOMEWORK,
    PERMISSIONS.VIEW_HOMEWORK,
    PERMISSIONS.ENTER_MARKS,
    PERMISSIONS.CALCULATE_RESULTS,
    PERMISSIONS.SUBMIT_RESULTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS,
    PERMISSIONS.VIEW_COMMUNICATION
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.VIEW_STUDENTS,
    PERMISSIONS.MANAGE_STUDENTS,
    PERMISSIONS.VIEW_ADMISSIONS,
    PERMISSIONS.MANAGE_ADMISSIONS,
    PERMISSIONS.MARK_ATTENDANCE,
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS,
    PERMISSIONS.VIEW_COMMUNICATION
  ],
  [ROLES.PARENT]: [
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_TIMETABLE,
    PERMISSIONS.VIEW_HOMEWORK,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS,
    PERMISSIONS.VIEW_COMMUNICATION
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.VIEW_ATTENDANCE,
    PERMISSIONS.VIEW_TIMETABLE,
    PERMISSIONS.VIEW_HOMEWORK,
    PERMISSIONS.VIEW_FEES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.GENERATE_MARKSHEETS,
    PERMISSIONS.VIEW_COMMUNICATION
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};
